# Generated by Django 4.1.7 on 2023-03-07 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "main_title",
                    models.CharField(
                        default="string stored in database", max_length=50
                    ),
                ),
                ("main_intro", models.TextField(blank=True, default="", null=True)),
                ("indiv_intro", models.TextField(blank=True, default="", null=True)),
            ],
            options={"verbose_name_plural": "Interface Configuration",},
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "patient_id",
                    models.CharField(
                        default="patient_1",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=50)),
                ("repetitions", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("repetition_num", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Not Available", "Not Available"),
                            ("In Progress", "In Progress"),
                            ("Received", "Received"),
                            ("Approved", "Approved"),
                        ],
                        default="Available",
                        max_length=13,
                    ),
                ),
                ("report_name", models.CharField(blank=True, max_length=52, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("deadline_date", models.DateField(blank=True, null=True)),
                ("submission_date", models.DateField(blank=True, null=True)),
                (
                    "reminder_sent",
                    models.CharField(
                        choices=[("yes", "yes"), ("no", "no")],
                        default="no",
                        max_length=3,
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="jobs.patient"
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="jobs.task",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Jobs",
                "ordering": ["patient_id", "task_id"],
            },
        ),
    ]
