# Generated by Django 4.1.7 on 2023-04-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_configuration_max_num_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="indiv_intro",
            field=models.TextField(
                blank=True,
                default="",
                null=True,
                verbose_name="Individual user table text",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="main_intro",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Main table text"
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="main_title",
            field=models.CharField(
                default="string stored in database",
                max_length=50,
                verbose_name="Project title",
            ),
        ),
    ]
